name: Build Linux Kernel for aarch64

on:
  workflow_dispatch:
  push:
    branches:
      - new_fork

jobs:
  build-arm64:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[action build]')
    steps:
      - name: Checkout workflow repo
        uses: actions/checkout@v4

      - name: Install dependencies and cross toolchain
        run: |
          sudo apt-get update 
          sudo apt-get install -y build-essential bc bison unzip flex libssl-dev libelf-dev libncurses5-dev curl cpio rsync gcc-aarch64-linux-gnu wget xz-utils tar device-tree-compiler u-boot-tools

      - name: 默认配置(ARCH=arm64)
        run: |
          # make ARCH=arm64 olddefconfig
      - name: 构建内核与模块 (ARCH=arm64)
        run: |
          make -j$(nproc) ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- all modules V=1
      - name: 生成模块 (ARCH=arm64)
        run: |
          INSTALL_MOD_PATH=$PWD/modules-out make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- modules_install
      - name: 打包tar.gz
        run: |
          mkdir artifact-out
          cp arch/arm64/boot/Image artifact-out/
          cp .config artifact-out/
          cp System.map artifact-out/
          cp vmlinux artifact-out/
          mv modules-out/* artifact-out/
          tar czf linux-arm64-artifacts.tar.gz -C artifact-out .
      - name: 上传打包
        uses: actions/upload-artifact@v4
        with:
          name: linux-aarch64-artifacts-2
          path: linux-arm64-artifacts.tar.gz
      - name: 发布
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          name: Linux Kernel aarch64 Build ${{ github.run_number }}
          tag_name: linux-arm64-build-${{ github.run_number }}
          files: linux-arm64-artifacts.tar.gz

